// myapp-React/src/App.js
import { useEffect, useRef, useState } from "react";
import "./App.css";

function App() {
  // State
  const [todos, setTodos] = useState([]);

  // Binding
  const todoText = useRef();

  // Side Effect / Lifecycle
  useEffect(() => {
    const existingTodos = localStorage.getItem("todos");
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);

  // Events
  function addTodo(event) {
    event.preventDefault();
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem("todos", JSON.stringify(next));
  }

  return (
    <div>
      <ul>
        {todos.map((todo) => (
          <li key={todo}>{todo}</li>
        ))}
      </ul>
      <form onSubmit={addTodo}>
        <input ref={todoText} />
        <input type="submit" value="Add Todo" />
      </form>
    </div>
  );
}

export default App;

// my-svelte-app/src/App.svelte
<script>
import { onMount } from "svelte";

	let todos = [];
	let todoText = '';

	onMount(() => {
		const existingTodos = localStorage.getItem('todos');
		todos = JSON.parse(existingTodos) || [];
	});

	function addTodo() {
		todos = [...todos, todoText];
		localStorage.setItem('todos', JSON.stringify(todos));
	}
</script>

<main>
	<ul>
		{#each todos as todo}
		<li>{todo}</li>
		{/each}
	</ul>
	<form on:submit|preventDefault={addTodo}>
		<input bind:value={todoText}>
		<input type="submit" value="Add todo">
	</form>
</main>

<style>

</style>
